### ISSUE TITLE
Housing_DFN_QFN silkscreen looks strange 

### ISSUE THREAD

**Issue by madworm** [KiCad/Housings_DFN_QFN.pretty#3]
Were these footprints machine created?

Especially with the smaller devices (e.g. DFN-10), the silkscreen looks really strange, pretty ugly, asymmetric...

**Comment by michal777** [comment]
Yes, they were.
How would you determine which pin is 1 if the footprints were symmetric?
Ugly? De gustibus non est disputandum. I love them :heart:
They were designed to be functional, not pretty. Adding too much artwork in silkscreen will increase courtyard which can't be accepted in high destiny applications.

**Comment by madworm** [comment]
It shows. And using a language that deservedly died out long ago doesn't make it any better. If the main target for these footprints is machine assembly, why bother with silkscreen at all. The P&P surely doesn't need it.

You know, I probably wouldn't have said anything, if a couple of decent looking QFN footprints hadn't been deleted from 'SMD_Packages' just recently, to save a couple of bytes presumably.

**Comment by michal777** [comment]
Silkscreen may be usefull in hand soldering, service, drawing pcb. We have library convention and we try to follow standards and good rules to make kicad library better. Most of nice looking footprints that were deleted didn't match kicad library convention. We can't keep them all because it would make a big mess. You can find them in github history. Please make a copy and use your own library if you don't accept the rules. Appearance of the silkscreen is not the most important for us.
Please look at:
http://www.pcblibraries.com/forum/smt-library-silkscreen-outlines_topic26.html

**Comment by madworm** [comment]
Footprints that suddenly vanish are the least useful.

We're talking about a couple of bytes here, negligible. As those footprints are part of the repository's history anyway, would a "deprecated" folder have been out of the question? Much nicer than hunting through commits for deleted files.

**Comment by michal777** [comment]
Maybe it will be good to create some repo where we will put footprints we don't want in official library but even if it will be created much footprints will be added, deleted, renamed, moved, changed. I don't think it's good to keep duplicates - it will make a huge mess, even worse than this we have now. Probably it will be more difficult to find some old verision of footprint in huge "deprecated" library than to find it in github history.
It's better to make and keep offline copy of libraries and use them. Github libraries are continuously developed and changes (sometimes extensive) must be considered.

**Comment by CarlPoirier** [comment]
Michal is right on. Sorry madworm, but I am not even considering a "deprecated.pretty" library. All footprints that have been deleted were replaced by some compatible newer ones.

**Comment by SchrodingersGat** [comment]
Closing this due to lack of discourse.
