### ISSUE TITLE
DFN-12-1EP_3x3mm_Pitch0.50mm

### ISSUE THREAD

**Issue by hackscribble** [KiCad/Housings_DFN_QFN.pretty#33]
I need a 0.5mm pitch version of the DFN-12-1EP_3x3mm but there is just the 0.45mm version in the repo.

I'm happy to add as an individual item, or update the source script (if these footprints were script generated). 

@SchrodingersGat I note that you made some updates a few months ago - was that by script?

**Comment by SchrodingersGat** [comment]
I don't remember - can you point me to those changes?

**Comment by hackscribble** [comment]
This was the commit I spotted - updates to 70+ files

https://github.com/KiCad/Housings_DFN_QFN.pretty/commit/763e34a56daca9fbb0fab42673701a52a67a0183

**Comment by SchrodingersGat** [comment]
Oh, yes that one was a custom script that just updated _existing_ footprints, not generated from scratch. I don't have a script to create these.

**Comment by hackscribble** [comment]
Thanks @SchrodingersGat I will modify one of the existing footprints and submit a PR.
