### ISSUE TITLE
Missing QFN24 3x3mm

### ISSUE THREAD

**Issue by ssfrr** [KiCad/Housings_DFN_QFN.pretty#4]
I need a 3x3mm QFN24 package for the Inventsense MPU-9250 chip.

Can this be added, or can you point to the script that created these so I can add one myself?

Thanks.

**Comment by michal777** [comment]
Here is: https://github.com/michal777/Packages_Generator

pack_generator is pack_generator.c compiled on linux (can be compiled on windows). In pack_param/LIBRARY_NAME there are files with parameters of packages. To make package proper file with parameters must be written (even lines - description of parameters given in odd lines), then the executable must be run:
./pack_generator LIBRARY_NAME/PARAM_FILE_NAME (or script generate_packages may be used)
It will be saved in footprints/LIBRARY_NAME.pretty

I could do it but it can be hard to find good datasheet with land pattern and package drawings (I'd prefer not try to guess the parameters).

**Comment by CarlPoirier** [comment]
Spencer, would you like to share what you generated?

**Comment by ssfrr** [comment]
After wrestling with KiCad for a bit more I ended up switching over to Altium, so I never ended up getting the footprint generator up and running. Sorry I can't be more helpful!

-s

**Comment by keruseykaryu** [comment]
Is this will be suitable?

    (module QFN-24-1EP_3x3mm_Pitch0.4mm (layer F.Cu) (tedit 551439DF)
      (descr "24-Lead Plastic QFN (3mm x 3mm); Pitch 0.4mm")
      (tags "QFN 0.4")
      (attr smd)
      (fp_text reference REF** (at 0 -3.25) (layer F.SilkS)
        (effects (font (size 1 1) (thickness 0.15)))
      )
      (fp_text value QFN-24-1EP_3x3mm_Pitch0.4mm (at 0 3.25) (layer F.Fab)
        (effects (font (size 1 1) (thickness 0.15)))
      )
      (fp_line (start 2.025 -2.025) (end 2.025 2.025) (layer F.CrtYd) (width 0.05))
      (fp_line (start 2.025 2.025) (end -2.025 2.025) (layer F.CrtYd) (width 0.05))
      (fp_line (start -2.025 2.025) (end -2.025 -2.025) (layer F.CrtYd) (width 0.05))
      (fp_line (start -2.025 -2.025) (end 2.025 -2.025) (layer F.CrtYd) (width 0.05))
      (fp_line (start -1.6 1.6) (end -1.6 1.2) (layer F.SilkS) (width 0.15))
      (fp_line (start -1.6 1.6) (end -1.2 1.6) (layer F.SilkS) (width 0.15))
      (fp_line (start 1.6 1.6) (end 1.6 1.2) (layer F.SilkS) (width 0.15))
      (fp_line (start 1.6 1.6) (end 1.2 1.6) (layer F.SilkS) (width 0.15))
      (fp_line (start 1.6 -1.6) (end 1.6 -1.2) (layer F.SilkS) (width 0.15))
      (fp_line (start 1.6 -1.6) (end 1.2 -1.6) (layer F.SilkS) (width 0.15))
      (fp_line (start -1.6 -1.6) (end -1.2 -1.6) (layer F.SilkS) (width 0.15))
      (pad 1 smd rect (at -1.5 -1) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 2 smd rect (at -1.5 -0.6) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 3 smd rect (at -1.5 -0.2) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 4 smd rect (at -1.5 0.2) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 5 smd rect (at -1.5 0.6) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 6 smd rect (at -1.5 1) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 7 smd rect (at -1 1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 8 smd rect (at -0.6 1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 9 smd rect (at -0.2 1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 10 smd rect (at 0.2 1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 11 smd rect (at 0.6 1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 12 smd rect (at 1 1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 13 smd rect (at 1.5 1) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 14 smd rect (at 1.5 0.6) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 15 smd rect (at 1.5 0.2) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 16 smd rect (at 1.5 -0.2) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 17 smd rect (at 1.5 -0.6) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 18 smd rect (at 1.5 -1) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 19 smd rect (at 1 -1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 20 smd rect (at 0.6 -1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 21 smd rect (at 0.2 -1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 22 smd rect (at -0.2 -1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 23 smd rect (at -0.6 -1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 24 smd rect (at -1 -1.5 90) (size 0.55 0.2) (layers F.Cu F.Paste F.Mask))
      (pad 25 smd rect (at 0.435 0.4) (size 0.875 0.8) (layers F.Cu F.Paste F.Mask)
        (solder_paste_margin_ratio -0.2))
      (pad 25 smd rect (at 0.435 -0.4) (size 0.875 0.8) (layers F.Cu F.Paste F.Mask)
        (solder_paste_margin_ratio -0.2))
      (pad 25 smd rect (at -0.435 0.4) (size 0.875 0.8) (layers F.Cu F.Paste F.Mask)
        (solder_paste_margin_ratio -0.2))
      (pad 25 smd rect (at -0.435 -0.4) (size 0.875 0.8) (layers F.Cu F.Paste F.Mask)
        (solder_paste_margin_ratio -0.2))
    )

**Comment by CarlPoirier** [comment]
@ssfrr Alright, have fun.

@keruseykaryu Looks great. You can commit it directly.

**Comment by keruseykaryu** [comment]
> @keruseykaryu Looks great. You can commit it directly.

Done.
